#!/bin/bash
user=root

mysqlport=3370
mysqlhost=win70.inno.com
#MYSQL_CONN="mysqladmin --login-path=mon"
#MYSQL_CONN="mysqladmin -u$user -p$pwd -h$mysqlhost -P$mysqlport"
MYSQL_CONN="mysqladmin --login-path=root"
MYSQLE_CONN="mysql --login-path=root"

if [ $# -ne "1" ]; then
	echo "arg error"
fi

case $1 in 
	uptime)
		result=`$MYSQL_CONN status|grep -v mysqladmin|cut -f2 -d":"|cut -f1 -d"T"`
		echo $result
   		;;
	Com_update)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_update"|cut -d "|" -f3`
		echo $result
   		;;
	Com_select)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_select"|cut -d "|" -f3`
		echo $result
   		;;

	Com_insert)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_insert"|cut -d "|" -f3`
		echo $result
   		;;

	Com_delete)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_delete"|cut -d "|" -f3`
		echo $result
   		;;

	Com_begin)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_begin"|cut -d "|" -f3`
		echo $result
   		;;

	Com_commit)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_commit"|cut -d "|" -f3`
		echo $result
		;;

	Com_rollback)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Com_rollback"|cut -d "|" -f3`
		echo $result
		;;

	Questions)
		result=`$MYSQL_CONN status|grep -v mysqladmin|cut -f4 -d ":"|cut -f1 -d"S"`
		echo $result
		;;

	Slow_queries)
		result=`$MYSQL_CONN status|grep -v mysqladmin|cut -f5 -d":"|cut -f1 -d"O"`
		echo $result
   		;;

	Open_table)
		result=`$MYSQL_CONN status|grep -v mysqladmin|cut -f8 -d":"|cut -f1 -d"Q"`
		echo $result
   		;;

	Bytes_sent)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Bytes_sent"|cut -d"|" -f3`
		echo $result
   		;;

	Bytes_received)
		result=`$MYSQL_CONN extended-status|grep -v mysqladmin|grep -w "Bytes_received"|cut -d"|" -f3`
		echo $result
   		;;

	table_locks_immediate)
		result=`$MYSQLE_CONN "-e show status like 'table_locks_immediate'"|grep -i "Table"|cut -f2`
		echo $result
   		;;

	table_locks_waited)
		result=`$MYSQLE_CONN "-e show status like 'table_locks_waited'"|grep -i "Table"|cut -f2`
		echo $result
   		;;

	innodb_row_lock_current_waits)
		result=`$MYSQLE_CONN "-e show status like 'innodb_row_lock_current_waits'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;
	innodb_row_lock_time)
		result=`$MYSQLE_CONN "-e show status like 'innodb_row_lock_time'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;
	innodb_row_lock_time_avg)
		result=`$MYSQLE_CONN "-e show status like 'innodb_row_lock_time_avg'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;
	innodb_row_lock_time_max)
		result=`$MYSQLE_CONN "-e show status like 'innodb_row_lock_time_max'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;

	innodb_row_lock_waits)
		result=`$MYSQLE_CONN "-e show status like 'innodb_row_lock_waits'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;

	Innodb_buffer_pool_pages_free)
		result=`$MYSQLE_CONN "-e show status like 'Innodb_buffer_pool_pages_free'"|grep -i "Innodb"|cut -f2`
		echo $result
   		;;
		
	*)
	
	echo "usge:$0 (uptime|com_update|slow_queries)"
		;;
esac