#!/bin/bash
#=============================================================================
# HEADER
#=============================================================================
#% SYNOPSIS
#%    ${prog}
#%
#% DESCRIPTION
#%    Script to create mysql slave 
#%
#% ARGUMENTS
#%    directory
#%
#% EXAMPLES
#%    ${prog} target_hostname backup_dir
#%
#=============================================================================
#  HISTORY
#     20220104  innod motingxia@163.com
#=============================================================================
#  NOTES
#=============================================================================
# END_OF_HEADER
#=============================================================================

#=============================================================================
#  IMPORT COMMON FUNCTIONS AND VARIABLES
#=============================================================================
RUNDIR="$(cd "$(dirname "${0}")" && pwd)"
if [ -z "${FUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions.ksh
fi
if [ -z "${MYSQLFUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions_mysql.ksh
fi
#=============================================================================
#  FUNCTIONS
#=============================================================================
do_exit() {
    RC=$1
    echo "$RC" >/tmp/RC.$$
    exit $RC
}

if [ $# -lt 1 ]; then
    usage
    exit 8
fi

RC=0
log_info "stat time $(date)"
scriptname=$(basename $0)
starttime=$(date +%s)
log_info "start time ${starttime}"
if ! [ -f ${LOG_FILE_DIR}/${scriptname}.log  ];then
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
else
    rm -rf ${LOG_FILE_DIR}/${scriptname}.log
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
fi
export LogFile=${LOG_FILE_DIR}/${scriptname}.log
log_info  "logfile: ${LogFile}"

#=============================================================================
#  FUNCTION
#=============================================================================
stratslave(){
    mysqlconfigeditor="/tmp/mysqlconfigurefile"
    log_info "start setup --login-path=superman"
    ssh ${targethost} "eval ${mysqlconfigeditor}"
    ssh ${targethost} "mysqladmin --login-path=superman status"
    if [ $? -eq 0 ]; then
        log_info "setup mysql --login-path=superman done!!"
        check_file ${mysqlconfigeditor}
    else 
        log_error "setup mysql --login-path=sumperman failed"
        do_exit 8
    fi


    
    setslavefile="/tmp/setms.${targethost}"
    log_info   "start setup slave on ${targethost} successfully "
    ssh ${targethost} "mysql --login-path=superman -e 'show processlist;'"
    ssh ${targethost} "mysql --login-path=superman <${setslavefile}" 
    if [ $? = "0" ]; then
        log_info   "setup slave on ${targethost} successfully "
        check_file ${setslavefile}
    else
        log_error   "ERROR setup slave on ${targethost} failed"
        do_exit 4
    fi
}

runas_root

targethost=$1
targetip=$(get_ip ${targethost})
stratslave

# } 2>&1 |tee -a $LogFile

if [ -f /tmp/RC.$$ ]; then
    RC=$(cat /tmp/RC.$$)
    rm -f /tmp/RC.$$
fi
log_info "RC=${RC}"
if [ "$RC" == "0" ]; then
    log_info   "OK: EndofScript ${scriptname} "    | tee -a $LogFile
else
    log_error  "ERROR: EndofScript ${scriptname} " | tee -a $LogFile
fi

ende=$(date +%s)
diff=$((ende - starttime))
log_info     "$(date)   Runtime      :   $diff"  | tee -a $LogFile
log_info     "Save log to ${LogFile}         "   | tee -a $LogFile
echo -e "setup  slave user repl on ${starttime} with password : ${replpassword}"|mail -s "deploy slave  RC=$RC on $(hostname)" motingxia@163.com
echo -e "superman password : ${supermanpassword}"|mail -s "superman password on $(hostname)" motingxia@163.com
logrename  ${LogFile}
exit ${RC}