#!/bin/sh
#chkconfig: 2345 80 05
#description: elasticsearch
export ES_JAVA_HOME=/data/elasticsearch/jdk
export JAVA_HOME=/data/elasticsearch/jdk
export PATH=$ES_JAVA_HOME/bin:$JVAVA_HOME/bin:/data/elasticsearch/bin:$PATH
export PATH=$PATH:/data/kibana/bin

case "$1" in
start)
    su - es -c '/data/elasticsearch/bin/elasticsearch -d'
    echo "elasticsearch startup"
    ;;  
stop)
    es_pid=`ps aux|grep elasticsearch | grep -v 'grep elasticsearch' | awk '{print $2}'`
    kill -9 $es_pid
    echo "elasticsearch stopped"
    ;;  
restart)
    es_pid=`ps aux|grep elasticsearch | grep -v 'grep elasticsearch' | awk '{print $2}'`
    kill -9 $es_pid
    echo "elasticsearch stopped"
    su - es -c '/data/elasticsearch/bin/elasticsearch -d &'
    echo "elasticsearch startup"
    ;;  
*)
    echo "start|stop|restart"
    ;;  
esac
exit $?
