#!/bin/sh
#chkconfig: 2345 80 05
#description: metribeat
export ES_JAVA_HOME=/data/metribeat/jdk
export JAVA_HOME=/data/metribeat/jdk
export PATH=$ES_JAVA_HOME/bin:$JVAVA_HOME/bin:/data/metricbeat:$PATH
export PATH=$PATH:/data/kibana/bin

case "$1" in
start)
    /data/metricbeat/metricbeat -c /data/metricbeat/metricbeat.yml &
    echo "metribeat startup"
    ;;  
stop)
    es_pid=`ps aux|grep metribeat | grep -v 'grep metribeat' | awk '{print $2}'`
    kill -9 $es_pid
    echo "metribeat stopped"
    ;;  
restart)
    es_pid=`ps aux|grep metribeat | grep -v 'grep metribeat' | awk '{print $2}'`
    kill -9 $es_pid
    echo "metribeat stopped"
    /data/metricbeat/metricbeat -c /data/metricbeat/metricbeat.yml &
    echo "metribeat startup"
    ;;  
*)
    echo "start|stop|restart"
    ;;  
esac
exit $?
