#!/bin/sh
#chkconfig: 2345 80 05
#description: metribeat
export ES_JAVA_HOME=/home/kibana/jdk
export JAVA_HOME=/home/kibana/jdk
export PATH=$ES_JAVA_HOME/bin:$JVAVA_HOME/bin:/home/filebeat:$PATH
export PATH=$PATH:/home/kibana/bin

case "$1" in
start)
    /home/filebeat/filebeat -c /home/filebeat/filebeat.yml &
    echo "metribeat startup"
    ;;  
stop)
    es_pid=`ps aux|grep metribeat | grep -v 'grep metribeat' | awk '{print $2}'`
    kill -9 $es_pid
    echo "metribeat stopped"
    ;;  
restart)
    es_pid=`ps aux|grep metribeat | grep -v 'grep metribeat' | awk '{print $2}'`
    kill -9 $es_pid
    echo "metribeat stopped"
    /home/filebeat/filebeat -c /home/filebeat/filebeat.yml &
    echo "metribeat startup"
    ;;  
*)
    echo "start|stop|restart"
    ;;  
esac
exit $?
