#!usr/bin/ksh
#=============================================================================
# HEADER
#=============================================================================
#% SYNOPSIS
#%    ${prog}
#%
#% DESCRIPTION
#%    Script to deploy mysql service
#%
#% ARGUMENTS
#%    NONE
#%
#% EXAMPLES
#%    ${prog}
#%    sh parallers inst
#%                 start
#%                 stop 
#%                 restart
#%                 post   (reset inist password ant set login-path=root)
#=============================================================================
#  HISTORY
#     20220601  ainnod motingxia@163.com
#=============================================================================
#  NOTES
#=============================================================================
# END_OF_HEADER
#=============================================================================

#=============================================================================
#  IMPORT COMMON FUNCTIONS AND VARIABLES
#=============================================================================
RUNDIR="$(cd "$(dirname "${0}")" && pwd)"
if [ -z "${FUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions.ksh
fi
if [ -z "${MYSQLFUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions_mysql.ksh
fi
#=============================================================================
#  FUNCTIONS
#=============================================================================
do_exit() {
    RC=$1
    echo "$RC" >/tmp/RC.$$
    exit $RC
}

if [ $# -lt 1 ]; then
    usage
    exit 8
fi

RC=0
scriptname=$(basename $0)
starttime=$(date +%s)
if ! [ -f ${LOG_FILE_DIR}/${scriptname}.log ]; then
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
else
    rm -rf ${LOG_FILE_DIR}/${scriptname}.log
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
fi
export LogFile=${LOG_FILE_DIR}/${scriptname}.log
log_info  "logfile: ${LogFile}"
source ~/.bash_profile

exec_counter
#=============================================================================
#  root_login_path
#=============================================================================

mysqlinit() {
    
    mysqlstop

    log_info "delete ${mysql_undo_dir} "
    rm -rf ${mysql_undo_dir}/*
    log_info "delete ${mysql_binlog_dir} "
    rm -rf ${mysql_binlog_dir}/*
    log_info "delete ${mysql_data_dir} "
    rm -rf ${mysql_data_dir}/*
    log_info "delete ${mysql_log_dir} "
    rm -rf ${mysql_log_dir}/*
    log_info "delete ${mysql_pid_dir} "
    rm -rf ${mysql_pid_dir}/*

    Generatet_Mysql_cnf

    source /root/.bash_profile
    mysqld --defaults-file=${mysqlcnf} --basedir=${basedir} --datadir=${mysql_data_dir} --user=mysql --initialize  
    if [ $? -eq 0 ]; then
        log_info "initialize mysql db successfully"
    else 
        log_error "initialize mysql db failed"
        do_exit 8
    fi
    check_file "/tmp/mysql.sock"
    check_file "/tmp/mysqlx.sock"
    ln -sf  ${mysql_pid_dir}/mysql.sock /tmp/mysql.sock
    ln -sf  ${mysql_pid_dir}/mysqlx.sock /tmp/mysqlx.sock
    log_info "mysql datbase initial setup done! " 
    log_info "waiting 10 seconds"
    sleep 10s
    # ${basedir}/support-files/mysql.server
    autostart
    root_login_path
    mysqlstartup
    # sh ${RUNDIR}/logpath
}

#=============================================================================
#  mysql startup
#=============================================================================
mysqlstartup(){
    if [ $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|grep -v $0|wc -l) -eq 0 ];then
        log_info "mysql is not running, start it now"
    else 
        log_warning "mysql is running,no need to start"
        do_exit 4
    fi
    # (mysqld_safe --defaults-file=${mysqlcnf} --user=mysql &) 2>/dev/null 1>/dev/null           #不卡主 但是本程序下MySQL登录不上
    # {mysqld_safe --defaults-file=${mysqlcnf} --user=mysql }    &  1>/dev/null 2>/dev/null  #不工作
    # mysqld_safe --defaults-file=${mysqlcnf} --user=mysql &  1>/dev/null 2>/dev/null          #卡主 不继续执行
    # nohup mysqld_safe --defaults-file=${mysqlcnf} --user=mysql &  1>/dev/null 2>/dev/null      #卡主 不继续执行
    # (exec mysqld_safe --defaults-file=${mysqlcnf} --user=mysql &) 2>/dev/null 1>/dev/null  #不卡主 但是本程序下MySQL登录不上
    systemctl start mysqld
    sleep 2
    # mysqld_safe --defaults-file=${mysqlcnf} --user=mysql 1>/dev/null 2>/dev/null &

    if [ $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|grep -v $0|wc -l) -eq 0 ]; then
        log_warning "looks like mysql started is not work"
        log_warning "try with mysql restarted failed"
        systemctl restart mysqld
        if [ $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|grep -v $0|wc -l) -eq 2 ];then
            log_info "mysql started successfully"
        fi
        # log_warning "restart system is required"
        # sleep 5
        mysqladmin --login-path=root processlist
    else 
        log_error "mysql started failed"
        do_exit 8
    fi
}
#=============================================================================
#  mysql stop
#=============================================================================
mysqlstop(){
    if [ $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|wc -l) -eq 0 ];then
        log_info "mysql is down"
    fi
    while true 
        do 
            if [ $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|wc -l) -eq 0 ];then
                log_info "mysql is not running"
                break
            else
                mysqladmin --login-path=root shutdown
                if [ $? -eq 0 ]; then
                    log_info "mysql is shutdown"
                else
                    log_warning "kill mysql process"
                    for i in $(ps -ef|grep -i mysql|grep -v grep|grep -v restore|grep -v $0|awk '{print $2}');do kill -9 $i;done
                    log_warning   "mysql process are killed"
                    break
                fi
            fi
        done
}
#=============================================================================
#  mysql autostart
#=============================================================================
autostart()
{
log_info "copy ${basedir}/support-files/mysql.server to /etc/init.d/mysqld"
if [ ! -f /etc/init.d/mysqld ]; then
    # cp -p ${basedir}/mysql/support-files/mysql.server /etc/init.d/mysqld
    log_info "genareate /etc/init.d/mysqld"
else 
    log_warning "/etc/init.d/mysqld already exist"
fi
sed -e "46,47d" -e "45i\basedir=${basedir}" -e "48i\datadir=${datadir}" /usr/local/mysql/support-files/mysql.server >/etc/init.d/mysqld
chown mysql:mysql /etc/init.d/mysqld
chmod +x /etc/init.d/mysqld
log_info "copy done"
log_info "add mysql start up as OS"
if [ `chkconfig --list|grep -i mysql|wc -l` -eq 1 ];then
    log_warning "mysqld already there"
else
    chkconfig --add mysqld
    log_info "add mysql start up as OS up done"
fi
chkconfig mysqld on
if [ -f /etc/my.cnf.d/my.cnf ]; then
    log_warning "/etc/my.cnf.d/ already exist" 
fi
log_info "copy ${mysqlcnf} to  /etc/"
echo y|cp -p ${mysqlcnf} /etc/
chown mysql:mysql /etc/my.cnf.d/
log_info "copy ${mysqlcnf} to  /etc/my.cnf done"
systemctl daemon-reload
}
#=============================================================================
#  mysql setup login path
#=============================================================================
root_login_path() {
    log_info "prepare mysql --login-path=root script"
    #rmove already exist login-path
    if [ -f ~/.mylogin.cnf ]; then
        rm -rf ~/.mylogin.cnf
        log_info "exist ~/.mylogin.cnf removed"
    fi

    # create_file "/tmp/loginpathfile"
    # mysqlconfigeditor="/tmp/loginpathfile"
    # echo "#!/usr/bin/expect -f "                                                                                                          >>${mysqlconfigeditor}
    # echo "spawn mysql_config_editor set --login-path='root' --user='root' --host='localhost' --socket=${mysql_pid_dir}/mysql.sock --password" >>${mysqlconfigeditor}
    # echo "expect -nocase \"Enter password:\" {send \"$initpwd\r; interact}"                                                   >>${mysqlconfigeditor}
    # chmod +x ${mysqlconfigeditor}
    # log_info "prepare mysql --login-path=root script done!!!"
    # log_info "start setup --login-path=root"
    # eval ${mysqlconfigeditor}

unbuffer expect -c "
spawn mysql_config_editor set --login-path=root --host='localhost' --socket='${mysql_pid_dir}/mysql.sock' --user='root' --password
expect -nocase \"Enter password:\" {send \"$newpassword\r\"; interact}
"

    if [ $? -eq 0 ]; then
        log_info "setup mysql --login-path=root done!!"
        mysqladmin --login-path=root processlist
    else 
        log_error "setup mysql --login-path=root failed"
        do_exit 8
    fi
}
#=============================================================================
#  change init password after init mysql
#=============================================================================
changeinitpassword() {
    log_info "get initial password from mysql"
    initpwd=`grep "A temporary password is generated for root@localhost: " ${mysql_log_dir}/error.log`
    initpwd=${initpwd##*root@localhost:}
    initpwd=${initpwd// /}
    newpassword=$(head /dev/urandom |cksum |md5sum |cut -c 1-12)
    log_info "initial password: ${initpwd}"
    echo "${mysql_pid_dir} ${newpassword}"
    source /etc/profile.d/mysql.sh
    #  source ~/.bash_profile

    # check_file "/tmp/resetpasswd"
    # ressetpw="/tmp/resetpasswd"
    # echo "mysql -uroot -p\"${initpwd}\" --host="localhost" --socket="${mysql_pid_dir}/mysql.sock" --connect-expired-password -e \"alter user 'root'@'localhost' identified by '${newpassword}';\"" >>${ressetpw}
    ### (mysql --user="root" --password="${initpwd}" --host="localhost" --socket="${mysql_pid_dir}/mysql.sock" --connect-expired-password -e "alter user 'root'@'localhost' identified by '${newpassword}';" &)
    ### mysql --user="root" --password="${initpwd}" --host="localhost" --socket="${mysql_pid_dir}/mysql.sock" --connect-expired-password -e "alter user 'root'@'localhost' identified by '${newpassword}';" 
    # mysql -uroot -p${initpwd} -S ${mysql_pid_dir}/mysql.sock --connect-expired-password -e "alter user 'root'@'localhost' identified by '${newpassword}';" 
    mysql -uroot -p"${initpwd}" --host="localhost" --socket="${mysql_pid_dir}/mysql.sock" --connect-expired-password -e "alter user 'root'@'localhost' identified by '${newpassword}';"
    # mysql -uroot -p${initpwd} -S ${mysql_pid_dir}/mysql.sock --connect-expired-password -e "alter user 'root'@'localhost' identified by   '${defaultPwd}';"
    # chmod +x ${ressetpw}
    # ssh $(hostname) "sh ${ressetpw}" >/dev/null
    if [ $? -eq 0 ]; then
        log_info "password reseted successfully"   
    else 
        log_error "password reseted failed"       
        do_exit 8
    fi
    log_info "new password: ${newpassword}" 
    echo -e "deploy mysql at ${starttime} with password : ${newpassword}" | mail -s "deploy mysql result RC=$RC on $(hostname)" motingxia@163.com
}
#=============================================================================
# install plugin
#=============================================================================

# sqlexe() {
#     # if [ $(mysql --login-path=root  -e "show plugins;"|grep -i $1 |wc -l) -eq 0 ]; then
#     # if [ $(mysql --login-path=root  -e "show plugins;"|grep -i $1 |wc -l) -eq 0 ]; then
#     # mysql --login-path=root -e "install plugin rpl_semi_sync_master soname '$1';"
#     mysql --login-path=root -e "$1;"
#     if [ $? -eq 0 ];then
#             log_info "$1 exectue successfully ok"
#     else
#             log_error "$1 runnning failed"
#             do_exit 8
#     fi

#     # ?else 
#         # log_alert "$1 already install"
#     # fi
# }

#=============================================================================
# main
#=============================================================================
case $1 in
    start)
        mysqlstartup
        ;;
    stop)
        mysqlstop
        ;;
    inst)
        mysqlinit
        ;;
    post)
        changeinitpassword
        root_login_path
        ;;
    restart)
        mysqlstop
        log_info "waitting for mysql to stop..."
        sleep 5
        mysqlstartup
        ;;
    *)
        usage
        ;;
esac

# mysqladmin --login-path=root processlist

log_info ""
log_info "RC==${RC}"
log_info ""                               

if [[ -f /tmp/RC.$$ ]];then
    RC=$(cat /tmp/RC.$$)
    rm -rf /tmp/RC.$$
fi
if [ "$RC" == "0" ]; then
    log_info   "OK: EndofScript ${scriptname}"    | tee -a ${LogFile}
else
    log_error  "ERROR: EndofScript ${scriptname} " | tee -a ${LogFile}
fi
ende=$(date +%s)
diff=$((ende - starttime))
log_info    "$(date)   Runtime      :   $diff" | tee -a ${LogFile} 
log_info    "Save log to ${LogFile}"           | tee -a ${LogFile} 
logrename  ${LogFile}
exit ${RC}