#!usr/bin/ksh
#=============================================================================
# HEADER
#=============================================================================
#% SYNOPSIS
#%    ${prog}
#%
#% DESCRIPTION
#%    Script to deploy mysql service
#%
#% ARGUMENTS
#%    NONE
#%
#% EXAMPLES
#%    ${prog}
#%    sh parallers inst
#%                 start
#%                 stop 
#%                 restart
#%                 rootlogin
#=============================================================================
#  HISTORY
#     20220601  ainnod motingxia@163.com
#=============================================================================
#  NOTES
#=============================================================================
# END_OF_HEADER
#=============================================================================

#=============================================================================
#  IMPORT COMMON FUNCTIONS AND VARIABLES
#=============================================================================
RUNDIR="$(cd "$(dirname "${0}")" && pwd)"
if [ -z "${FUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions.ksh
fi
if [ -z "${MYSQLFUNCTIONS_IMPORTED}" ]; then
    . ${RUNDIR}/functions_mysql.ksh
fi
#=============================================================================
#  FUNCTIONS
#=============================================================================
do_exit() {
    RC=$1
    echo "$RC" >/tmp/RC.$$
    exit $RC
}

if [ $# -lt 1 ]; then
    usage
    exit 8
fi

RC=0
scriptname=$(basename $0)
starttime=$(date +%s)
if ! [ -f ${LOG_FILE_DIR}/${scriptname}.log ]; then
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
else
    rm -rf ${LOG_FILE_DIR}/${scriptname}.log
    touch ${LOG_FILE_DIR}/${scriptname}.log
    LogFile=${LOG_FILE_DIR}/${scriptname}.log
fi
export LogFile=${LOG_FILE_DIR}/${scriptname}.log
log_info  "logfile: ${LogFile}"
source ~/.bash_profile

exec_counter
#=============================================================================
#  root_login_path
#=============================================================================

{
mysql --login-path=root -e "$1;" >>/tmp/mysql_result
if [ $? -eq 0 ];then
    log_info "$1 exectue successfully ok"
else
    log_error "$1 runnning failed"
    do_exit 8
fi


# mysqladmin --login-path=root processlist

log_info ""
log_info "RC==${RC}"
log_info ""                               
} 2>&1 | tee -a ${LogFile}

if [[ -f /tmp/RC.$$ ]];then
    RC=$(cat /tmp/RC.$$)
    rm -rf /tmp/RC.$$
fi
if [ "$RC" == "0" ]; then
    log_info   "OK: EndofScript ${scriptname}"    | tee -a ${LogFile}
else
    log_error  "ERROR: EndofScript ${scriptname} " | tee -a ${LogFile}
fi
ende=$(date +%s)
diff=$((ende - starttime))
log_info     "$(date)   Runtime      :   $diff"| tee -a ${LogFile} 
log_info     "Save log to ${LogFile}" | tee -a ${LogFile} 
logrename  ${LogFile}
exit ${RC}